name: LanderFestive
version: '${project.version}'
main: me.landeryt.landerfestive.LanderFestive
api-version: '1.20'
load: STARTUP
commands:
  christmas:
    description: A festive command
    usage: /<command>

