name: Commands1
version: '${project.version}'
main: me.landeryt.commands1.Commands1
api-version: '1.20'
load: STARTUP
commands:
  die:
    description: An easy way to kill yourself.
    usage: /<command>