orange-sheep: true
eat-beets: true
cauldron: true
killed-by-endermite: true
eat-cake: true

bat-kill: true
invis-death: true
moss-lantern: true

snowman-shear: true
phantom-kill: true

enderman-kill: true