name: NoEnd
version: '${project.version}'
main: me.landeryt.noend.NoEnd
api-version: '1.20'
load: STARTUP
authors: [LanderYT]
description: Prevents players from finding the stronghold by disallowing eye of enders
