name: Configurations
version: '${project.version}'
main: me.landeryt.configurations.Configurations
api-version: '1.20'
load: STARTUP
authors: [LanderYT]
commands:
  setjoinmessage:
    description: Sets the join message
    usage: /<command>
    permission: configurations.setjoinmessage
permissions:
  configuration.setjoinmessage:
    default: op
    description: Allows the user to set the server join message
